version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: log/info.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: simple
        filename: log/warn.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: log/error.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

loggers:
    job:
        level: WARN
        handlers: [warn_file_handler, error_file_handler]
        propagate: no
    audit.remove:
        level: WARN
        handlers: [warn_file_handler, error_file_handler]
        propagate: no
    audit.stage:
        level: WARN
        handlers: [warn_file_handler, error_file_handler]
        propagate: no
    utils:
        level: WARN
        handlers: [warn_file_handler, error_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, warn_file_handler, error_file_handler]